name: Release

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: tag
        uses: freckle/haskell-tag-action@v1
        with:
          package-yaml: persistent-sql-lifted/package.yaml
          tag-prefix: persistent-sql-lifted-v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: steps.tag.outputs.tag
        run: stack upload --pvp-bounds lower persistent-sql-lifted
        env:
          HACKAGE_KEY: ${{ secrets.HACKAGE_UPLOAD_API_KEY }}
          STACK_YAML: stack-lts20.yaml
